### ISSUE TITLE
Pages that should 404 are returning error 500 Internal Server Error

### ISSUE THREAD

**Issue by wiboticalex** [UAVCAN/uavcan.org#31]
For example: https://uavcan.org/404 returns an error 500 for me. Pages with content work as expected.

Also, I think this is potentially causing Google to blacklist you from search since it can't be sure if robots.txt is working or not (that returns error 500 too: https://uavcan.org/robots.txt)

**Comment by pavel-kirienko** [comment]
Thanks, Alex.

@clyde-johnston can you look into this?

**Comment by clyde-johnston** [comment]
This error is caused by a missing template in the html_error.html page.  I have removed this line and push the site to [UAT](http://uat.uavcan.org).  The site does not have a robots.txt file but this is unrelated to the 500 error.

Please check the [UAT](http://uat.uavcan.org) site.  If you are happy with the new behaviour, I will push it to production.  If a robots.txt file is needed, I can add this to the site before pushing to production.

**Comment by pavel-kirienko** [comment]
Thanks, Clyde, looks good to me. Do start a new pull request, please.

Regarding :robot:.txt, does it make sense for us to have it? We don't have any non-indexable pages.

**Comment by clyde-johnston** [comment]
> Thanks, Clyde, looks good to me. Do start a new pull request, please.

Done

> Regarding robot.txt, does it make sense for us to have it? We don't have any non-indexable pages.

It depends if you want it to be search-engine friendly.  Personally, I don't think it is necessary for this site but I could see arguments for having one anyway.  We could add one just register the content pages for the search engines.
